import React from 'react';
import Head from 'next/head';

import Header from 'components/Header';

import * as S from './styled';

const Home = () => (
  <S.Wrapper>
    <Head>
      <title>NEAshop</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <S.Main>Main</S.Main>
    <footer>Footer</footer>
  </S.Wrapper>
);

export default Home;
