import React from 'react';
import Head from 'next/head';

import Hero from 'components/Hero';
import ZigZagList from 'components/ZigZagList';

import * as S from './styled';

const Home = () => (
  <>
    <Head>
      <title>NEAshop</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <S.Wrapper>
      <Hero />
      <S.Main>
        <ZigZagList />
      </S.Main>
      <footer>Footer</footer>
    </S.Wrapper>
  </>
);

export default Home;
