import React from 'react';
import Head from 'next/head';

import Header from 'components/Header';

const Home = () => (
  <>
    <Head>
      <title>NEAshop</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <main />
    <footer />
  </>
);

export default Home;
